name: just_audio
description: Flutter plugin to play audio from streams, files, assets, DASH/HLS streams and playlists. Works with audio_service to play audio in the background.
version: 0.3.4
homepage: https://github.com/ryanheise/just_audio

environment:
  sdk: '>=2.6.0 <3.0.0'
  flutter: ">=1.12.8 <2.0.0"

dependencies:
  rxdart: ^0.24.1
  path: ^1.7.0
  path_provider: ^1.6.24
  async: ^2.4.2
  uuid: ^2.2.2
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.ryanheise.just_audio
        pluginClass: JustAudioPlugin
      ios:
        pluginClass: JustAudioPlugin
      macos:
        pluginClass: JustAudioPlugin
      web:
        pluginClass: JustAudioPlugin
        fileName: just_audio_web.dart
